stages:
    - test

Isort:
    stage: test
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    script:
        - pip install isort
        - isort backend/app/app
    after_script:
        - ./docs/get-updated-badge-isort.sh
    artifacts:
        paths:
            - ./isort-badges.json
        when: always
        expire_in: 1 weeks