stages:
    - test


Mypy:
    stage: test
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    script:
        - pip install mypy
        - mypy backend/app/app
    after_script:
        - ./get-updated-badge-info.sh
    artifacts:
        paths:
            - badges.json
        when: always
        expire_in: 4 weeks
