repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 . --max-line-length=120 --exclude=.venv
        language: system
        pass_filenames: false
  - repo: local
    hooks:
     - id: isort
       name: isort
       entry: isort . --recursive --check-only  --profile black
       language: system
       pass_filenames: false
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit .
        language: system
        pass_filenames: false
        args: [--recursive]
  - repo: local
    hooks:
     - id: mypy
       name: mypy
       entry: mypy .
       language: system
       pass_filenames: false
