default_context:
  project_name: 'App to-3d.com'
  project_slug: 'app-to-3d.com'
  domain_main: 'app.to-3d.com'
  domain_staging: 'stag.app.to-3d.com'
  docker_swarm_stack_name_main: 'app-to-3d-com'
  docker_swarm_stack_name_staging: 'stag-app-to-3d-com'
  secret_key: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  first_superuser: 'admin@app.to-3d.com'
  first_superuser_password: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.app.to-3d.com", "https://stag.app.to-3d.com", "https://app.to-3d.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@to-3d.com'
  postgres_password: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  pgadmin_default_user: 'admin@app.to-3d.com'
  pgadmin_default_user_password: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  traefik_constraint_tag: 'app.to-3d.com'
  traefik_constraint_tag_staging: 'stag.app.to-3d.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
