name: bandit

on: push

jobs:
  build:
    name: Bandit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: jpetrucciani/bandit-check@master
      with:
        bandit_flags: '-r $(pwd)/backend --exclude "$(pwd)/backend/app/app/tests"  --severity-level high  --confidence-level high'