name: mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    name: MyPy
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies and run MyPy
      run: |
        python -m venv venv
        source ./venv/bin/activate
        pip install poetry
        pip install --upgrade pip
        echo 1
        ls -la
        poetry env use 3.9
        echo 2
        ls -la
        cd backend/app
        echo 3
        ls -la
        poetry install
        ../../venv/bin/mypy ./
