name: PyTest

on: push

jobs:
  build:
    name: "PyTest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv venv
        source ./venv/bin/activate
        pip install --upgrade pip
        pip install poetry
        cd backend/app
        poetry install
    - name: Build coverage file
      run: |
        export $(cat .env|xargs)
        cd backend/app/app
        ../../../venv/bin/pytest --cache-clear --cov=app > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2